# Vivijure backend SEED image (#537) -- the immutable, versioned carrier for the curated model seed.
#
# WHY THIS EXISTS (#537)
# ----------------------
# The backend release bake used to re-stage the ~87 GB (bf16) / ~90 GB (fp8) curated seed from R2 and
# bin-pack it on EVERY backend-v* tag. That download + bin-pack is the dominant release cost. This
# image stages + bin-packs the seed ONCE per weights bump and publishes it as a versioned, immutable
# GHCR artifact:
#
#   ghcr.io/skyphusion-labs/vivijure-backend-seed:<model_version>-<precision>   (e.g. 1-bf16)
#
# The consuming backend Dockerfile pins this base by TAG AND DIGEST and COPY --from's the bins in,
# then verifies /seed-bins/weights-manifest.sha256 with `sha256sum -c` (a byte mismatch fails LOUD).
# The runner snapshot pre-pulls this image into the docker cache so a release bake is assemble+push
# only; a stale/absent snapshot degrades to a slow docker pull, NEVER to a wrong image.
#
# This is an ACCELERATOR + SOURCE OF TRUTH, not a runtime image: it carries NO CUDA/torch/app, only
# the weight bins + their checksum manifest + the third-party model licenses. The carrier OS
# (debian-slim) contributes NOTHING to the consumer image -- COPY --from extracts only /seed-bins.
#
# The bins are bin-packed by deploy/bake_layers.py into <10 GB layers (GHCR rejects a >=10 GB layer),
# each mirroring its path relative to VJ_MODELS_ROOT so their union reconstructs the HF cache +
# finish-model tree. The seed build workflow (.github/workflows/seed-build.yml) stages the
# seed from R2, reconstructs the HF-cache symlinks, bin-packs, writes the manifest, and asserts a real
# (non-hollow) weight set BEFORE this image is built -- so a hollow base can never be published.
#
# Build context is the REPO ROOT (so `COPY deploy/seed-bins/...` resolves). REQUIRES a staged +
# bin-packed seed: deploy/seed-bins/bin-00..bin-23 must exist (the workflow creates them). A build
# without them fails at the bake COPY by design.

FROM debian:bookworm-slim

# Provenance metadata (build args are stamped by the workflow). These label the artifact for audit;
# the authoritative pins are the tag+digest the consumer references and the checksum manifest below.
ARG VJ_BAKE_PRECISION=bf16
ARG VJ_MODEL_VERSION=1
LABEL org.opencontainers.image.title="vivijure-backend-seed" \
      org.opencontainers.image.description="Curated, bin-packed model seed for the vivijure-backend bake (source of truth)." \
      org.opencontainers.image.source="https://github.com/skyphusion-labs/vivijure-backend" \
      org.opencontainers.image.licenses="AGPL-3.0-or-later" \
      vivijure.bake.precision="${VJ_BAKE_PRECISION}" \
      vivijure.bake.model_version="${VJ_MODEL_VERSION}"

# ------------------------------------------------------------------ BAKED MODEL WEIGHTS (the bins)
# 24 bins, each < 9 GB (under the 10 GB GHCR per-layer ceiling), each mirroring paths relative to
# VJ_MODELS_ROOT. One COPY = one layer. Empty bins are harmless zero-byte layers (the workflow
# pre-creates all 24). This fixed list matches the consuming Dockerfile's COPY --from list exactly.
COPY deploy/seed-bins/bin-00/ /seed-bins/bin-00/
COPY deploy/seed-bins/bin-01/ /seed-bins/bin-01/
COPY deploy/seed-bins/bin-02/ /seed-bins/bin-02/
COPY deploy/seed-bins/bin-03/ /seed-bins/bin-03/
COPY deploy/seed-bins/bin-04/ /seed-bins/bin-04/
COPY deploy/seed-bins/bin-05/ /seed-bins/bin-05/
COPY deploy/seed-bins/bin-06/ /seed-bins/bin-06/
COPY deploy/seed-bins/bin-07/ /seed-bins/bin-07/
COPY deploy/seed-bins/bin-08/ /seed-bins/bin-08/
COPY deploy/seed-bins/bin-09/ /seed-bins/bin-09/
COPY deploy/seed-bins/bin-10/ /seed-bins/bin-10/
COPY deploy/seed-bins/bin-11/ /seed-bins/bin-11/
COPY deploy/seed-bins/bin-12/ /seed-bins/bin-12/
COPY deploy/seed-bins/bin-13/ /seed-bins/bin-13/
COPY deploy/seed-bins/bin-14/ /seed-bins/bin-14/
COPY deploy/seed-bins/bin-15/ /seed-bins/bin-15/
COPY deploy/seed-bins/bin-16/ /seed-bins/bin-16/
COPY deploy/seed-bins/bin-17/ /seed-bins/bin-17/
COPY deploy/seed-bins/bin-18/ /seed-bins/bin-18/
COPY deploy/seed-bins/bin-19/ /seed-bins/bin-19/
COPY deploy/seed-bins/bin-20/ /seed-bins/bin-20/
COPY deploy/seed-bins/bin-21/ /seed-bins/bin-21/
COPY deploy/seed-bins/bin-22/ /seed-bins/bin-22/
COPY deploy/seed-bins/bin-23/ /seed-bins/bin-23/

# The union-keyed SHA-256 manifest (deploy/bake_layers.py manifest): "<sha>  <union-path>" for every
# weight file, generated by the workflow over the bins. The consumer verifies it after its per-bin
# COPY --from with `cd /opt/models && sha256sum -c weights-manifest.sha256`. THIS is the byte-identity
# gate that makes a stale-snapshot / substituted-layer failure LOUD, not silent.
COPY deploy/seed-bins/weights-manifest.sha256 /seed-bins/weights-manifest.sha256

# Third-party model licenses (Apache-2.0 Sec 4(b), MIT, CreativeML RAIL++-M), carried alongside the
# weights so the consuming image is redistribution-compliant by construction. The finish-leg sha256
# pin record (bake-manifest.json) travels too so the consumer's assert-finish-shas has its pins.
COPY deploy/licenses /seed-bins/licenses
COPY deploy/bake-manifest.json /seed-bins/bake-manifest.json
